version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: laravel_user
        uid: 1000
    container_name: abprod_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    networks:
      - abprod_network
    command: bash -c "composer install --no-dev --ignore-platform-reqs && 
             mkdir -p /var/www/storage/logs /var/www/storage/framework/cache /var/www/storage/framework/sessions /var/www/storage/framework/views && 
             chmod -R 777 /var/www/storage /var/www/bootstrap/cache && 
             php artisan octane:start --server=swoole --host=0.0.0.0 --port=8081"

  mysql:
    image: mysql:8.0
    container_name: abprod_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: abprod
      MYSQL_ROOT_PASSWORD: ja_Riz657tH]
      MYSQL_PASSWORD: ja_Riz657tH]
      MYSQL_USER: abprod
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - abprod_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: abprod_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ja_Riz657tH]
    depends_on:
      - mysql
    networks:
      - abprod_network

volumes:
  mysql_data:
    driver: local

networks:
  abprod_network:
    driver: bridge
