version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8100:8100"
    volumes:
      - ./storage:/app/storage
      - ./bootstrap/cache:/app/bootstrap/cache
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=:memory: 