services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: abprod_app
    restart: unless-stopped
    ports:
      - "8100:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      - APP_ENV=local
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=abprod
      - DB_USERNAME=abprod
      - DB_PASSWORD=ja_Riz657tH]
    networks:
      - abprod_network

  mysql:
    image: mariadb:10.5
    container_name: abprod_mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=abprod
      - MYSQL_USER=abprod
      - MYSQL_PASSWORD=ja_Riz657tH]
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-config/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - abprod_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: abprod_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql
    networks:
      - abprod_network

volumes:
  mysql_data:

networks:
  abprod_network:
    driver: bridge
