services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: abprod_app
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      - APP_ENV=local
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=abprod
      - DB_USERNAME=abprod
      - DB_PASSWORD=ja_Riz657tH]
    networks:
      - abprod_network

  mysql:
    image: mysql:8.0
    container_name: abprod_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=abprod
      - MYSQL_USER=abprod
      - MYSQL_PASSWORD=ja_Riz657tH]
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_INNODB_BUFFER_POOL_SIZE=20M
      - MYSQL_INNODB_LOG_FILE_SIZE=10M
      - MYSQL_MAX_CONNECTIONS=10
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-innodb-read-only-compressed
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - abprod_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: abprod_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql
    networks:
      - abprod_network

volumes:
  mysql_data:

networks:
  abprod_network:
    driver: bridge
