version: '3.8'

services:
  laravel:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8100:8100"
    volumes:
      - ./storage:/app/storage
      - ./bootstrap/cache:/app/bootstrap/cache
    depends_on:
      - mysql
    networks:
      - laravel_network
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=abprod
      - DB_USERNAME=root
      - DB_PASSWORD=ja_Riz657tH]

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: abprod
      MYSQL_ROOT_PASSWORD: ja_Riz657tH]
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ja_Riz657tH]
      PMA_USER: root
      PMA_PASSWORD: ja_Riz657tH]
      UPLOAD_LIMIT: 300M
    depends_on:
      - mysql
    networks:
      - laravel_network

volumes:
  mysql_data:
    driver: local

networks:
  laravel_network:
    driver: bridge
