version: '3.8'

services:
  laravel:
    build: .
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mysql
    networks:
      - laravel_network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:your-app-key
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=abprod
      - DB_USERNAME=root
      - DB_PASSWORD=ja_Riz657tH]

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: abprod
      MYSQL_ROOT_PASSWORD: ja_Riz657tH]
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ja_Riz657tH]
    depends_on:
      - mysql
    networks:
      - laravel_network

volumes:
  mysql_data:

networks:
  laravel_network:
